### ISSUE TITLE
Bug Fixes 12/13/16 - 12/20/16

### ISSUE THREAD

**Issue by janjankev** [neigelYap/iDriveTheSecond#10]
1. Session Bug
2. Notification Enhancement (Color)
3. Tables (Pagination and Search)
4. Driver Manager to Data source
5. Array list session for Page redirect

**Comment by neigelYap** [comment]
Pagination and search (Done)

**Comment by neigelYap** [comment]
Notification Enhancement (Done)

**Comment by neigelYap** [comment]
localStorage.clear();

Possible fix for tab bug.

**Comment by neigelYap** [comment]
Session Bug (Done)
