### ISSUE TITLE
For Keith

### ISSUE THREAD

**Issue by janjankev** [neigelYap/iDriveTheSecond#21]
Penetration MASTER
Footer
Adjust PDF Cells

**Comment by neigelYap** [comment]
PDF Check for Desktop thingy

**Comment by janjankev** [comment]
http://developers.itextpdf.com/question/how-can-i-serve-pdf-browser-without-storing-file-server-side

**Comment by maxilosgundam** [comment]
Penetration  **ASSISTANT** MASTER - Ongoing
Footer - Ongoing
Adjust PDF Cells - Done

**Comment by maxilosgundam** [comment]
http://ryanfait.com/sticky-footer/

**Comment by maxilosgundam** [comment]
https://css-tricks.com/couple-takes-sticky-footer/
