### ISSUE TITLE
Client's Issue 1/24/2017

### ISSUE THREAD

**Issue by janjankev** [neigelYap/iDriveTheSecond#24]
- [x] Fit 2 trip ticket forms on same page.

- [x] Car coding

POX201
UIN502
OV1093
OW4150

- [x] add primary key to vehicle instead of plate number as primary key

**Comment by neigelYap** [comment]
Ask sir james about the deletion of departments, what department will the division head go to

**Comment by neigelYap** [comment]
Bug Found (by James): If the reservation has not yet been approved by either the admin or manager on or after the date, the reservation will still stay in the DB
